### PR TITLE
new implementation

### PR DESCRIPTION
**Pull request by jonsterling**
+ uses McBride-style scopes / "I'm Not A Number, I'm A Free Variable!"
+ uses Lean-style optimizations: in particular, keep track of a bound on de bruijn indices, as well as whether a term has any free variables, symbols in it.

### CODE REVIEW

**Comment by jonsterling** [comment]
I think that in order to make proper sort checking feasible, it will be necessary to store the free (variables, symbols, metas) + their sorts as part of the "system annotation" for each term. This will also make `symctx, varctx, metactx` instantaneous.

**Comment by jonsterling** [comment]
Some further optimizations are suggested in the MetaPRL project, http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.71.6688&rep=rep1&type=pdf.

* don't calculate free variables until needed (be lazy)
* when applying a substitution, trim the variables from the substitution that are not free in the term
* apply substitutions lazily: this means add "explicit substitution" terms to the internal representation, and force them as soon as anything needs to look at the term.

**Comment by jonsterling** [comment]
Anyway, we shouldn't over-optimize before we try it out and compare it with the other implementation.

**Comment by jonsterling** [comment]
@favonia I'm seeing more than 50% speedup in RedPRL with this implementation vs the old one! It will get even faster too once I figure out how to correctly optimize `instantiate` (my attempted optimization has some de bruijn index arithmetic wrong, so I disabled it).

**Comment by favonia** [comment]
Yay! Did you burn the documents with closures yet?

**Comment by jonsterling** [comment]
@favonia I haven't burnt it yet, but I will soon...

**Comment by jonsterling** [comment]
The implementation is still not quite correct (I can tell, because certain proofs don't work in RedPRL :rofl: )

**Comment by jonsterling** [comment]
Now, I understand why the code is wrong; I don't yet know how to fix it, but knowing the problem is the first step. stay tuned.

**Comment by jonsterling** [comment]
OK, now that the code is actually correct, the observed performance improvement in RedPRL is around 40%.

**Comment by favonia** [comment]
How did you measure the speedup?

**Comment by jonsterling** [comment]
@favonia Caveman-style:  running `time redprl test/success/connection.prl` several times (which is the most computationally intensive proof that we have)

**Comment by favonia** [comment]
You are forcing me to define the Ackermann function...

**Comment by jonsterling** [comment]
@favonia Lol!

**Pull request merged**
